# ©AngelaMos | 2026
# .rubocop.yml

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "vendor/**/*"
    - "target/**/*"
    - "docs/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 30

Metrics/ClassLength:
  Max: 250

Layout/LineLength:
  Max: 120
